baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "adamtiger.github.io/ai" # the base hostname & protocol for your site.
title: "Everything about ML, RL and AI"

paginate: 10 #articles per page
paginate_path: /ml/page:num #makes pagination working

#contacts
git: "https://github.com/adamtiger"  #your github url here.

#disqus comment
disqus:
    shortname: "DISQS" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title
markdown: maruku

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
